# Packet sizes in bytes
packet_sizes:
  IMAGE: 3072  # 32*32*3
  block0: 262144  # 256*32*32
  block1: 131072  # 512*16*16
  block2: 65536  # 1024*8*8
  block3: 65536  # 1024*8*8

# Block processing times in seconds
block_processing_times:
  mobilenetv2:
    block0: 0.008451
    block1: 0.010490
    block2: 0.010306
    block3: 0.011895
  resnet18:
    block0: 0.027375
    block1: 0.023139
    block2: 0.022367
    block3: 0.041036
  resnet50:
    block0: 0.068596
    block1: 0.069558
    block2: 0.097112
    block3: 0.101480

# Block CPU FLOPS (floating-point operations per second)
block_cpu_flops:
  mobilenetv2:
    block0: 1237000  # 1.237M FLOPs
    block1: 1223000  # 1.223M FLOPs 
    block2: 623296  # 623.296K FLOPs
    block3: 1764000  # 1.764M FLOPs
  resnet18:
    block0: 154145000  # 154.145M FLOPs
    block1: 134915000  # 134.915M FLOPs
    block2: 134579000  # 134.579M FLOPs
    block3: 134387000  # 134.387M FLOPs
  resnet50:
    block0: 226182000  # 226.182M FLOPs
    block1: 339773000  # 339.773M FLOPs
    block2: 481101000  # 481.101M FLOPs
    block3: 265081000  # 265.081M FLOPs

# Agent time in seconds
agent_time: 0.001

# Current draw in mA for each operation
current_draw:
  mobilenetv2:
    processing: 40  # mA for processing
    transmission: 90  # mA for transmission
  resnet18:
    processing: 50  # mA for processing
    transmission: 100  # mA for transmission
  resnet50:
    processing: 60  # mA for processing
    transmission: 110  # mA for transmission
  idle: 1  # mA for idle state

# Battery parameters
battery:
  initial_charge: 2000  # mAh
  capacity: 2000  # mAh
  discharge_rate: 0.05  # mA per hour when idle
  voltage: 3.7  # Volts (typical for Li-ion batteries)

# Simulation parameters
simulation:
  max_sim_time: 50000
  stability_window: 2000
  stability_threshold: 0.03
  evaluation_time: 1000

# DQL Agent parameters
dql_agent:
  memory_size: 100000
  batch_size: 64
  gamma: 0.99
  learning_rate: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  update_frequency: 10

# Early Exit parameters
early_exit:
  confidence_threshold: 0.8

# Model selection
model: "resnet18"  # Options: "mobilenetv2", "resnet18", "resnet50"

# Dataset selection
dataset: "tiny-imagenet"  # Options: "cifar10", "cifar100", "flame2", "tiny-imagenet"
